export const SEARCH_START_REQUEST = "SEARCH_START_REQUEST";
export const SEARCH_START_SUCCESS = "SEARCH_START_SUCCESS";
export const SEARCH_START_FAIL = "SEARCH_START_FAIL";

export const READ_RESULTS_REQUEST = "READ_RESULTS_REQUEST";
export const READ_RESULTS_SUCCESS = "READ_RESULTS_SUCCESS";
export const READ_RESULTS_FAIL = "READ_RESULTS_FAIL";

export const CLEAR_DATA = "CLEAR_DATA";
