export const SEARCH_START_REQUEST = "SEARCH_START_REQUEST";
export const SEARCH_START_SUCCESS = "SEARCH_START_SUCCESS";
export const SEARCH_START_FAIL = "SEARCH_START_FAIL";

export const READ_RESULTS_REQUEST = "READ_RESULTS_REQUEST";
export const READ_RESULTS_SUCCESS = "READ_RESULTS_SUCCESS";
export const READ_RESULTS_FAIL = "READ_RESULTS_FAIL";

export const READ_FILTERS_REQUEST = "READ_FILTERS_REQUEST";
export const READ_FILTERS_SUCCESS = "READ_FILTERS_SUCCESS";
export const READ_FILTERS_FAIL = "READ_FILTERS_FAIL";

export const READ_FILTERED_RESULTS_REQUEST = "READ_FILTERED_RESULTS_REQUEST";
export const READ_FILTERED_RESULTS_SUCCESS = "READ_FILTERED_RESULTS_SUCCESS";
export const READ_FILTERED_RESULTS_FAIL = "READ_FILTERED_RESULTS_FAIL";

export const CLEAR_CATALOG_DATA = "CLEAR_CATALOG_DATA";
