export const SEARCH_FORM_REQUEST = "SEARCH_FORM_REQUEST";
export const SEARCH_FORM_SUCCESS = "SEARCH_FORM_SUCCESS";
export const SEARCH_FORM_FAIL = "SEARCH_FORM_FAIL";

export const SEARCH_START_REQUEST = "SEARCH_START_REQUEST";
export const SEARCH_START_SUCCESS = "SEARCH_START_SUCCESS";
export const SEARCH_START_FAIL = "SEARCH_START_FAIL";

export const READ_RESULTS_REQUEST = "READ_RESULTS_REQUEST";
export const READ_RESULTS_SUCCESS = "READ_RESULTS_SUCCESS";
export const READ_RESULTS_FAIL = "READ_RESULTS_FAIL";

export const GET_TOUR_REQUEST = "GET_TOUR_REQUEST";
export const GET_TOUR_SUCCESS = "GET_TOUR_SUCCESS";
export const GET_TOUR_FAIL = "GET_TOUR_FAIL";
