export const SEARCH_FORM_REQUEST = "SEARCH_FORM_REQUEST";
export const SEARCH_FORM_SUCCESS = "SEARCH_FORM_SUCCESS";
export const SEARCH_FORM_FAIL = "SEARCH_FORM_FAIL";

export const GET_FLIGHTS_INFO_REQUEST = "GET_FLIGHTS_INFO_REQUEST";
export const GET_FLIGHTS_INFO_SUCCESS = "GET_FLIGHTS_INFO_SUCCESS";
export const GET_FLIGHTS_INFO_FAIL = "GET_FLIGHTS_INFO_FAIL";