export const SEARCH_FORM_REQUEST = "SEARCH_FORM_REQUEST";
export const SEARCH_FORM_SUCCESS = "SEARCH_FORM_SUCCESS";
export const SEARCH_FORM_FAIL = "SEARCH_FORM_FAIL";

export const SEARCH_START_REQUEST = "SEARCH_START_REQUEST";
export const SEARCH_START_SUCCESS = "SEARCH_START_SUCCESS";
export const SEARCH_START_FAIL = "SEARCH_START_FAIL";

export const READ_RESULTS_REQUEST = "READ_RESULTS_REQUEST";
export const READ_RESULTS_SUCCESS = "READ_RESULTS_SUCCESS";
export const READ_RESULTS_FAIL = "READ_RESULTS_FAIL";

export const GET_TOUR_REQUEST = "GET_TOUR_REQUEST";
export const GET_TOUR_SUCCESS = "GET_TOUR_SUCCESS";
export const GET_TOUR_FAIL = "GET_TOUR_FAIL";

export const GET_OTHER_TOURS_REQUEST = "GET_OTHER_TOURS_REQUEST";
export const GET_OTHER_TOURS_SUCCESS = "GET_OTHER_TOURS_SUCCESS";
export const GET_OTHER_TOURS_FAIL = "GET_OTHER_TOURS_FAIL";

export const GET_FLIGHTS_INFO_REQUEST = "GET_FLIGHTS_INFO_REQUEST";
export const GET_FLIGHTS_INFO_SUCCESS = "GET_FLIGHTS_INFO_SUCCESS";
export const GET_FLIGHTS_INFO_FAIL = "GET_FLIGHTS_INFO_FAIL";

export const GET_HOT_TOURS_REQUEST = "GET_HOT_TOURS_REQUEST";
export const GET_HOT_TOURS_SUCCESS = "GET_HOT_TOURS_SUCCESS";
export const GET_HOT_TOURS_FAIL = "GET_HOT_TOURS_FAIL";

export const GET_RECOMMENDED_TOURS_REQUEST = "GET_RECOMMENDED_TOURS_REQUEST";
export const GET_RECOMMENDED_TOURS_SUCCESS = "GET_RECOMMENDED_TOURS_SUCCESS";
export const GET_RECOMMENDED_TOURS_FAIL = "GET_RECOMMENDED_TOURS_FAIL";

export const GET_TOURS_BY_COUNTRY_REQUEST = "GET_TOURS_BY_COUNTRY_REQUEST";
export const GET_TOURS_BY_COUNTRY_SUCCESS = "GET_TOURS_BY_COUNTRY_SUCCESS";
export const GET_TOURS_BY_COUNTRY_FAIL = "GET_TOURS_BY_COUNTRY_FAIL";

export const GET_TOUR_REVIEWS_REQUEST = "GET_TOUR_REVIEWS_REQUEST";
export const GET_TOUR_REVIEWS_SUCCESS = "GET_TOUR_REVIEWS_SUCCESS";
export const GET_TOUR_REVIEWS_FAIL = "GET_TOUR_REVIEWS_FAIL";

export const CLEAR_DATA = "CLEAR_DATA";
