export const GET_HOT_TOURS_REQUEST = "GET_HOT_TOURS_REQUEST";
export const GET_HOT_TOURS_SUCCESS = "GET_HOT_TOURS_SUCCESS";
export const GET_HOT_TOURS_FAIL = "GET_HOT_TOURS_FAIL";

export const GET_RECOMMENDED_TOURS_REQUEST = "GET_RECOMMENDED_TOURS_REQUEST";
export const GET_RECOMMENDED_TOURS_SUCCESS = "GET_RECOMMENDED_TOURS_SUCCESS";
export const GET_RECOMMENDED_TOURS_FAIL = "GET_RECOMMENDED_TOURS_FAIL";