export const GET_TOURS_BY_COUNTRY_REQUEST = "GET_TOURS_BY_COUNTRY_REQUEST";
export const GET_TOURS_BY_COUNTRY_SUCCESS = "GET_TOURS_BY_COUNTRY_SUCCESS";
export const GET_TOURS_BY_COUNTRY_FAIL = "GET_TOURS_BY_COUNTRY_FAIL";
