export const GET_TOUR_REQUEST = "GET_TOUR_REQUEST";
export const GET_TOUR_SUCCESS = "GET_TOUR_SUCCESS";
export const GET_TOUR_FAIL = "GET_TOUR_FAIL";

export const GET_OTHER_TOURS_REQUEST = "GET_OTHER_TOURS_REQUEST";
export const GET_OTHER_TOURS_SUCCESS = "GET_OTHER_TOURS_SUCCESS";
export const GET_OTHER_TOURS_FAIL = "GET_OTHER_TOURS_FAIL";

export const GET_TOUR_REVIEWS_REQUEST = "GET_TOUR_REVIEWS_REQUEST";
export const GET_TOUR_REVIEWS_SUCCESS = "GET_TOUR_REVIEWS_SUCCESS";
export const GET_TOUR_REVIEWS_FAIL = "GET_TOUR_REVIEWS_FAIL";
